topics:
  Ruby on Rails:
    prompts: programming
    language: ruby
    settings:
      global:
        interactives:
          codepen: false
        allCodeInEditors: true

  Javascript:
    prompts: programming
    language: javascript
    settings:
      global:
        interactives:
          codepen: false
        allCodeInEditors: true

  Python:
    prompts: programming
    language: python
    settings:
      global:
        allCodeInEditors: true
        interactives:
          codepen: false

  HTML:
    prompts: programming
    language: python
    settings:
      global:
        interactives:
          codeEditor: false
      challenge:
        interactives:
          codepen: false
      final-skill-challenge:
        interactives:
          codepen: false
