topics:
  Ruby on Rails:
    prompts: programming
    language: ruby
    settings:
        hasInteractives: true # true by default
        interactives: # interactive settings
          codepen: false,
          counts: 
            lesson: 1
            challenge: 5
            final-skill-challenge: 20
          weights: # determines how often each type appears in the curriculum
            multipleChoice: 0.6
            codeEditor: 0.2
            codepen: 0.2
